image: Visual Studio 2017

install:
  - ps: $PSVersionTable
  - ps: .\install-modules.ps1 -Verbose

build_script:
  - ps: Import-Module .\posh-profile.psm1

test_script:
  - ps: |
        Set-Location .\test
        $testResultsFile = ".\TestsResults.xml"
        $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($results.FailedCount -gt 0)
        { 
            throw "$($results.FailedCount) tests failed."
        }
