image: Visual Studio 2017

install:
  - ps: $PSVersionTable
  - ps: .\install-modules.ps1 -Verbose

build_script:
  - ps: Import-Module .\posh-profile.psm1 -DisableNameChecking

test_script:
  - ps: |
        Set-Location .\test
        $testResultsFile = ".\TestsResults.xml"
        $results = Invoke-Pester -ExcludeTag 'NotAppVeyor' -OutputFormat NUnitXml -OutputFile $testResultsFile -CodeCoverage @('..\macAddressUtils.psm1', '..\posh-profile.psm1') -PassThru -Verbose
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        $codeCoverage = $results.CodeCoverage.NumberOfCommandsExecuted /( $results.CodeCoverage.NumberOfCommandsExecuted  + $results.CodeCoverage.NumberOfCommandsMissed)
        Write-Verbose "Code Coverage: $($codeCoverage*100) %" -Verbose
        if ($results.FailedCount -gt 0)
        { 
            throw "$($results.FailedCount) tests failed."
        }
