image: Visual Studio 2017

install:
  - ps: $PSVersionTable
  - ps: .\install-modules.ps1 -Verbose

build_script:
  - ps: Import-Module .\posh-profile.psm1 -DisableNameChecking

after_build:
  - choco install codecov

test_script:
  - ps: |
        $repoRoot = (Get-Location).Path
        Set-Location .\test
        $testResultsFile = ".\TestsResults.xml"
        $results = Invoke-Pester -ExcludeTag 'NotAppVeyor' -OutputFormat NUnitXml -OutputFile $testResultsFile -CodeCoverage @('..\macAddressUtils.psm1', '..\posh-profile.psm1') -PassThru -Verbose
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        $codeCoverage = $results.CodeCoverage.NumberOfCommandsExecuted /( $results.CodeCoverage.NumberOfCommandsExecuted  + $results.CodeCoverage.NumberOfCommandsMissed)
        Write-Verbose "Code Coverage: $($codeCoverage*100) %" -Verbose
        Save-Module -Name VSTS -Path . -RequiredVersion 1.0.189
        Import-Module .\VSTS\1.0.189\ci\CodeCovIo.psd1
        Export-CodeCovIoJson -CodeCoverage $results.CodeCoverage -RepoRoot $repoRoot -Path 'codeCov.json'
        if ($results.FailedCount -gt 0)
        { 
            throw "$($results.FailedCount) tests failed."
        }
  - codecov -f "codeCov.json" -t "fa2e7c3a-e65d-479a-872e-04d80549cdfe"